//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public Nullable<int> LabId { get; set; }
        public Nullable<double> GradeLab1 { get; set; }
        public Nullable<double> GradeLab2 { get; set; }
        public Nullable<double> GradeLab3 { get; set; }
        public Nullable<double> GradeLab4 { get; set; }
        public Nullable<double> GradeLab5 { get; set; }
        public Nullable<double> GradeLab6 { get; set; }
        public Nullable<double> GradeLab7 { get; set; }
        public Nullable<double> GradeLab8 { get; set; }
        public Nullable<double> GradeLab9 { get; set; }
        public Nullable<double> GradeLab10 { get; set; }
        public Nullable<double> GradeLab11 { get; set; }
        public Nullable<double> GradeLab12 { get; set; }
        public Nullable<double> GradeLab13 { get; set; }
        public Nullable<double> GradeLab14 { get; set; }
        public Nullable<double> FinaleGrade { get; set; }
    
        public virtual Lab Lab { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
