//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyYear
    {
        public StudyYear()
        {
            this.Labs = new HashSet<Lab>();
        }
    
        public int Id { get; set; }
        public string YearOfStudy { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Lab> Labs { get; set; }
    }
}
