//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaInfo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Department { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users1 { get; set; }
        public DbSet<Lab> Labs { get; set; }
        public DbSet<StudyYear> StudyYears { get; set; }
        public DbSet<ProfessorPerLab> ProfessorPerLabs { get; set; }
        public DbSet<Grade> Grades { get; set; }
    }
}
