//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProfessorPerLabs = new HashSet<ProfessorPerLab>();
            this.Grades = new HashSet<Grade>();
            this.Grades1 = new HashSet<Grade>();
        }
    
        public int UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Username { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<ProfessorPerLab> ProfessorPerLabs { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<Grade> Grades1 { get; set; }
    }
}
